# This is a basic workflow to help you get started with Actions

name: Test-vis

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the current branch you are working. 
  # It is advised to work on a feature branch and not the master/main branch.
  push:

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job Unit-tests"
  open-project-file:
    # Set the self hosted runner
    runs-on: self-hosted

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run VI Analyzer and Unit Test
        run: |
          g-cli --lv-ver 2020 --arch 64 "${{ github.workspace }}\Assignment\Project file\OpenProject.vi"
  
  
  test-vi:
    # Set the self hosted runner
    needs: open-project-file
    runs-on: self-hosted

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run VI Analyzer and Unit Test
        run: |
          g-cli --lv-ver 2020 --arch 64 "${{ github.workspace }}\Assignment\Assignment 1\Celsius to Farenheit\Tests\Test Convert.vi" -- -project-path "${{ github.workspace }}\Assignment\Assignment 1\Celsius to Farenheit\CelsiusToFarenheit.lvproj"

